Cumulative Rain = 
SWITCH(
    TRUE(),
    ISNUMBER([B/b1/Cumulative_rain]), VALUE([B/b1/Cumulative_rain]),
    [B/b1/Cumulative_rain] = "n/a", 0,
    0
)


Cleaned_Livestock_Affected = 
SWITCH(
    TRUE(),
    ISNUMBER('817841'[B/d2/Livestock_affected]), VALUE('817841'[B/d2/Livestock_affected]),
    '817841'[B/d2/Livestock_affected] = "n/a", 0,
    0
)
Cumulative Rain = 
IF('817841'[B/b1/Cumulative_rain] = "n/a", 0, IFERROR(VALUE('817841'[B/b1/Cumulative_rain]), 0))
